# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 42de68d0cc696912e8c24182d97f76ac9f4e1a5b732e9de369935a69990c2ecf6e6f6eecc49f072dbc5697bac9612d662ca276175ce9e9d1d75d58090710a6df

test:
  secret_key_base: 90800a56d7d449c4b53ba599aead3d6c0b3cd83dca20667714a8ea6cf721fff5fcea375efb1333c4483554b517241cb1ffa1d25f8d9cf2422906bc12d06ee633

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
